### ISSUE TITLE
Automatic saving

### ISSUE THREAD

**Issue by BlkPingu** [RasaHQ/whatlies#117]
I'm currently visualizing with plot_interactive() and due to the size of the embeddings and the amount of data it takes quite a while. 

Is there any way to save the plot automatically in a given format, as I would with `plt.savefig('myplot.png')` `both.transform(Tsne(2)).plot_interactive('tsne_0', 'tsne_1',color='set', annot=False)` when I come from something like this?

Because as far as I can tell you have no option of this kind documented.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
Have you seen [the FAQ](https://rasahq.github.io/whatlies/faq/#plotting) on the documentation? Altair *can* save to json/html/svg/png.

**Comment by koaning** [comment]
Out of curiosity, you mention it takes a while because of the amount of data. Are your embeddings big or are you plotting many of them?

**Comment by BlkPingu** [comment]
> Out of curiosity, you mention it takes a while because of the amount of data. Are your embeddings big or are you plotting many of them? Altair only offers a few thousands of points to be plotted.

It's like 2gb worth of embeddings with dimensions of 100.000 x 700 so yea kinda big but not enormous or something
