### ISSUE TITLE
ndim attribute

### ISSUE THREAD

**Issue by mkaze** [RasaHQ/whatlies#122]
@koaning Do you think it's a good idea to add a `ndim` (or `size`) attribute for `Embedding` class which gives the dimension of embedding vector? And what about the `EmbeddingSet`? For `EmbeddingSet` this makes sense only if all the embedding vectors in it have the same length (which I think is an implicit assumption so far; although, one might argue that this is not a necessary condition to hold for all applications).

**Comment by koaning** [comment]
Seems sensible. Though technically we'd implement this on the embedding object.

```python
@property
def shape(self):
    return self.vector.shape[0]
```

I don't mind the feature, but it feels slightly verbose considering the info is also on the shape.

**Comment by koaning** [comment]
What might be a better name `shape` or `ndim`? I think I prefer `shape` mainly to keep the numpy standard alive.

**Comment by mkaze** [comment]
Numpy uses all of `shape`, `ndim` and `size` attributes, each with their own definition. To me, `shape` makes sense when we are dealing with N-D arrays; but here we know that the embedding vector is just a ..... vector! `ndim` might not be a good option as well since it means "number of dimensions" in Numpy; but here, for the same reason that I just mentioned, it would be clear that what `ndim` means here (especially when we say things like "10 dimensional vector" or "3D vector"; also [see this](https://math.stackexchange.com/q/2152360/174388)).

> I don't mind the feature, but it feels slightly verbose considering the info is also on the shape.

I just suggested it for the case of a more complete public API and user-friendly way of finding out the size of an embedding vector (e.g. the user might not care or know that under the hood we are using Numpy to represent the embedding vectors, and/or how to use them).

**Comment by koaning** [comment]
You've convinced me! Let's go for `ndim`.
