### ISSUE TITLE
Allow embeddings to be passed as *args

### ISSUE THREAD

**Issue by koaning** [RasaHQ/whatlies#124]
If `foo` is an `Embedding` instance, `EmbeddingSet(foo)` is not supported. Currently we need to write;

```
EmbeddingSet({'foo': foo})
```

It would be nicer if we also allow the aforementioned approach.

**Comment by mkaze** [comment]
To be clear the problem is that an `EmbeddingSet` containing a **single** `Embedding` cannot be constructed with `EmbeddingSet(foo)` (otherwise `EmbeddingSet(foo, bar)` works).

**Comment by koaning** [comment]
Why should that not be possible? We can check the type being passed in and behave accordingly right?

**Comment by mkaze** [comment]
> Why should that not be possible? We can check the type being passed in and behave accordingly right?

That's right! I did not mean that it is impossible to do; rather I meant that does not happen currently, as [when a single element is passed, it is assumed to be a dictionary](https://github.com/RasaHQ/whatlies/blob/master/whatlies/embeddingset.py#L44-L45).

**Comment by koaning** [comment]
Ah right. Clear!
