### ISSUE TITLE
Integer Default Parameters for Plotting Methods

### ISSUE THREAD

**Issue by koaning** [RasaHQ/whatlies#125]
The goal is to allow for this syntax; 

```python
emb.transform(Pca(2)).plot(x_axis=0, y_axis=1)
```

The reasoning is currently you have to write;

```python
emb.transform(Pca(2)).plot(x_axis="pca_0", y_axis="pca_1")
```

This get's annoying when you want to replace the `Pca` with `Umap`. 

```python
emb.transform(Umap(2)).plot(x_axis="umap_0", y_axis="umap_1")
```

What's even nicer is that with proper default arguments in the future you can just run; 

```python
emb.transform(Umap(2)).plot()
```

**Comment by mkaze** [comment]
I am working on a PR addressing this.

**Comment by mkaze** [comment]
@koaning One question: what would be the appropriate default axis labels in this case?

**Comment by koaning** [comment]
I think `x_axis=0` and `y_axis=1` should suffice, no?

**Comment by mkaze** [comment]
No, I mean the values for `xlabel` and `ylabel` in `handle_2d_plot`. For example, "D0" or "Dim 0" is good?

**Comment by koaning** [comment]
In the case that an `Embedding` is passed I would still much prefer that we use the associated name. I suppose if we use a dimension then `Dimension X` where `X` is the index?

**Comment by mkaze** [comment]
@koaning Having implemented and merged this feature, now how do we want to go about handling those `pca_0`, `pca_1`, etc. embeddings? Do we want to entirely remove them, or make them optional (e.g. for backwards compatibility) by adding a separate argument in the `__init__` method of corresponding transformer classes, e.g. `def __init__(self, ..., add_indicators=False)`? Or any other option?

**Comment by koaning** [comment]
Something inside me feels that making them optional is maybe the best choice but rationally I'm having a hard time giving a clear example of why this is a must. 

There's a transformer in there called `AddRandom` which is supposed to add random vectors to the EmbeddingSet. Before, I would have argued that this is a use-case for which we must have the vectors added but now I wonder if there's maybe an easier way. You can also just create a random EmbeddingSet yourself and just merge it with the original one.

I suppose it feels "safe" to make them optional, mainly because there's a feeling of "I might be forgetting about something". Then again, I'm having a hard time coming up with a proper-usecase. 

Implementation wise, it'd be amazing to just be able to drop them all-together. This should vastly simplify the transformers because we can essentially wrap around the scikit-learn API.

**Comment by mkaze** [comment]
@koaning Let's close this issue (since I think it's fully resolved now) and continue the discussion for handling helper vectors in #199.
