### ISSUE TITLE
Default representation of an EmbeddingSet

### ISSUE THREAD

**Issue by mkaze** [RasaHQ/whatlies#128]
Currently, an `EmbeddingSet` is [by default](https://github.com/RasaHQ/whatlies/blob/5ab7c0ad5dbc940a668d94559a5a8b430b49fc70/whatlies/embeddingset.py#L42) represented as `'Emb'`, same as an `Embedding` (e.g. `Emb [king]`). Isn't it better to use a distinctive name instead, e.g. `EmbSet`?

**Comment by koaning** [comment]
I can certainly see the merit there. To be honest I feel like the representation is something amazing for explaining how the arithmetic on single embeddings work but I've never really used them beyond this. 

I think I wouldn't want to rely the `__repr__` too much as a feature for embeddingsets It's a "nice to have" but not a "epic must".

**Comment by mkaze** [comment]
Yeah, I mostly encounter this in Jupyter Notebooks where `__repr__` is used by default. Although, the `__str__` for `EmbeddingSet` is the same.
