### ISSUE TITLE
Support for alternative axis projection metrics in plots

### ISSUE THREAD

**Issue by mkaze** [RasaHQ/whatlies#129]
Consider that `emb` is an embedding set and we run `emb.plot(x_axis='man', y_axis='woman')`. This would compute the normalized scalar projection (i.e. operator `>`) of every embedding in `emb` onto embeddings for `'man'` and `'woman'` so that they could be plotted in a 2D coordinate system. 

Now the question is: why we should only stick to normalized scalar projection? For example, one might want to use another measure such as cosine similarity or euclidean distance to plot the embeddings. 

- First of all, does this make sense? (to me, yes!)
- Secondly, is there currently an easy and built-in way to achieve this? (AFAIK, no!)
- Thirdly, is adding an argument to `plot` and `plot_interactive` methods to support this a good way? e.g. `emb.plot(x_axis='man', y_axis='woman', axis_metric='cosine')`.

**Comment by koaning** [comment]
I had been thinking about this too. I even remember implementing something like this a while ago. Got lost in one of my notebooks. As long as the currently implementation remains the default then I am all in favor.

**Comment by koaning** [comment]
Crazy idea. 

Do we ever want to measure "cosine distance of vector man" on the x-axis and "euclidean distance of vector man" on the y axis?

**Comment by mkaze** [comment]
> Do we ever want to measure "cosine distance of vector man" on the x-axis and "euclidean distance of vector man" on the y axis?

I am not sure of the application, but I had that in mind that someone may want to set different metric for each axis and it could be done easily using a list:
```python
emb.plot(x_axis='man', y_axis='woman', axis_metric=['cosine', 'euclidean'])
```
Even they could provide a function that takes two vectors and give a scalar in return:

```python
emb.plot(x_axis='man', y_axis='woman', axis_metric=np.dot)
```

**Comment by koaning** [comment]
I can agree to this API. It may be good to see if we can split up some of the logic so that it's easy to unit test (visualisations are hard to unit test) but I think being able to add custom functions here for visualisation is epic. 

What's potentially especially powerful here is that you can come up with statistical functions that ignore the x/y-axis but can still show useful information. Maybe that use-case is better served with another plotting function though. For this issue, let's just stick to the API as defined above.

**Comment by koaning** [comment]
I'm opening this issue because technically the issue should also be added to the `plot_interactive` methods.

**Comment by mkaze** [comment]
> I'm opening this issue because technically the issue should also be added to the plot_interactive methods.

@koaning Right! That's why I mentioned "partially" in #192 :wink:
