### ISSUE TITLE
Dependency Installation goes Awry

### ISSUE THREAD

**Issue by koaning** [RasaHQ/whatlies#139]
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/1019791/90245768-94d66b80-de33-11ea-8f36-a1a53bbcdcc1.png">

If I have a new virtualenv with no `tensorflow-text` then we can still get silly import errors. Need to fix this.

**Comment by koaning** [comment]
After installing `tensorflow-text` we get this: 

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/1019791/90246011-00b8d400-de34-11ea-8d62-4eeadb78b75f.png">.

**Comment by mkaze** [comment]
Ah, yeah right.... I thought you have used conditional imports when you made the dependency PR?! I completely forgot to mention that then (though, I vaguely remember I have mentioned it somewhere?!... I don't know where!). This certainly needs to be fixed.

**Comment by koaning** [comment]
It's also the transfromers. 

<img width="830" alt="image" src="https://user-images.githubusercontent.com/1019791/90246682-6c4f7100-de35-11ea-9681-d50ce752851d.png">

**Comment by koaning** [comment]
@mkaze Yeah something went wrong here. I'm curious why the tests passed too. Probably good to iterate on both soonish. I might have time in a few hours to start working on this.

**Comment by mkaze** [comment]
.> I'm curious why the tests passed too.

The answer is easy: because no test is run in `dependencies` workflow; rather, just the package is installed.

**Comment by koaning** [comment]
I suppose we could run some one-line import statements as an alternative. That's what we're interested in testing anyway.
