### ISSUE TITLE
Return value of fit method in transformers

### ISSUE THREAD

**Issue by mkaze** [RasaHQ/whatlies#153]
A suggestion: isn't it a good idea that the `fit` method in all the transformers return the object instance, i.e. `self`, so that we could chain `fit` and `transform` methods, like in:

```python
pca = Pca(...)
pca.fit(embset_1).transform(embset_2)
```
@koaning I can push a PR for that if you are agreed with this.

**Comment by mkaze** [comment]
Yeah, that's right. Mostly I had consistency with scikit-learn in my mind when I was thinking about this.

**Comment by koaning** [comment]
It might be good to perhaps add one extra feature now that I think of it. There could be confusion in terms of "can we also `Pca` in scikit-learn? I think the change is still good but maybe we should add an error message in case the user confuses the `PCA` from scikit-learn with the `Pca` from this library.

**Comment by mkaze** [comment]
In general case, we might be able to check if the argument passed to `transform` method is either an instance of `Transform` class, or is a callable (for functions).
