### ISSUE TITLE
Redo `add_property`

### ISSUE THREAD

**Issue by koaning** [RasaHQ/whatlies#155]
Currently [the docs](https://rasahq.github.io/whatlies/tutorial/transformations/) describe how to add properties to an `EmbeddingSet` which can later be used for plotting. 

```python
from whatlies.language.language import SpacyLanguage
lang = SpacyLanguage('en_core_web_sm')

words1 = ["dog", "cat", "mouse", "deer", "elephant", "zebra", "fish",
          "rabbit", "rat", "tomato", "banana", "coffee", "tea", "apple", "union"]
words2 = ["run", "swim", "dance", "sit", "eat", "hear", "look", "run", "stand"]

umap = Umap(2)
emb1 = lang[words1].transform(umap).add_property('set', lambda d: 'set-one')
emb2 = lang[words2].transform(umap).add_property('set', lambda d: 'set-two')

both = emb1.merge(emb2)
```

I think we can do slightly better here. This would be much nicer: 

```python
umap = Umap(2)
emb1 = lang[words1].transform(umap).add_property(set=lambda d: 'set-one')
emb2 = lang[words2].transform(umap).add_property(set=lambda d: 'set-two')
```

The benefit of this is that you can add multiple properties in one call. The usecase here is that this allows you to run a clustering algorithm on the dataset and then attach the cluster-id as a property on each embedding. 

Since this is a breaking change I would propose that we might deprecate `add_property` in favor of  another name. But first I'd like to check what other people might think.  @mkaze ?

**Comment by mkaze** [comment]
> The usecase here is that this allows you to run a clustering algorithm on the dataset and then attach the cluster-id as a property on each embedding.

Funny! I just saw this after mentioning the same thing in the other issue :smile: 

> Since this is a breaking change I would propose that we might deprecate add_property in favor of another name. But first I'd like to check what other people might think. @mkaze ?

I am in favor of the whole idea; however, I am not sure whether we should use a new method with a new name for that, or just make a backwards-incompatible change! Either has its own pros/cons.

**Comment by koaning** [comment]
I might argue that `assign` can also be seen as a nicer "verb" here. Mainly because this is the method that pandas uses for a very similar operation.
