### ISSUE TITLE
Update Language Options Documentation

### ISSUE THREAD

**Issue by koaning** [RasaHQ/whatlies#160]
We've added *a lot* of language backends but we've not updated the docs in a while. 

https://rasahq.github.io/whatlies/tutorial/languages/

It'd be good to also add/mention gensim, tfhub, huggingface.

**Comment by Ayushsunny** [comment]
> We've added _a lot_ of language backends but we've not updated the docs in a while.
> 
> https://rasahq.github.io/whatlies/tutorial/languages/
> 
> It'd be good to also add/mention gensim, tfhub, huggingface.

This link is throwing error- 404

**Comment by koaning** [comment]
Correct. We've since removed that part of the docs. This issue is therefore stale and can be closed.
