### ISSUE TITLE
Another way of constructing an EmbeddingSet

### ISSUE THREAD

**Issue by mkaze** [RasaHQ/whatlies#161]
Shouldn't we support initializing an `EmbeddingSet` using a list of names and an array/list/iterable of vectors:

```python
vecs = np.random.rand(3,4)
names = ['foo', 'bar', 'buz']

embset = EmbeddingSet(names, vecs)
# or
embset = EmbeddingSet.from_names_vecs(names, vecs)
```
Currently the most concise way of writing this is like: `EmbeddingSet(*[Embedding(n,v) for zip(names, vecs)])`. It sounds a common use case to me (for example in some of the transformers when used in `transform` method), but it shouldn't be that verbose to achieve! Preferably, it could also handle duplicate names by using the vector associated with the last occurrence of a name (which is automatically handled if we use something like `self.embeddings = {n:v for n, v in zip(names, vecs)}` in its implementation).

@koaning What do you think?

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @b-quachtran will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
I like it!
