### ISSUE TITLE
A method to get names and vectors of an EmbeddingSet

### ISSUE THREAD

**Issue by mkaze** [RasaHQ/whatlies#162]
Suggested:
```python
names, X = embset.to_names_vecs()
```
The most concise way to achieve it with current API:
```python
names = list(embset.embeddings.keys())
X = embset.to_X()
```
Besides its potential use case, this could replace the utility function `embset_to_X` which is used in transformers. 
Further, I have a feeling, which I don't know is good or not, that the need for the end-user to access `embeddings` property of `EmbeddingSet` should be minimal since it's mostly an implementation logic.

**Comment by mkaze** [comment]
Although, this could be achieved another way as well:
```
X,  names = embset.to_X_y('name')
```
Though, that's a bit weird...... but works anyways!

**Comment by koaning** [comment]
In this case `name` can also refer to a property?

**Comment by mkaze** [comment]
> In this case `name` can also refer to a property?

Yes, that's basically what you have implemented for that purpose, i.e. to get custom properties.

**Comment by koaning** [comment]
I'm certainly open to a method like `embset.to_names_vecs()` I'm wondering if we can come up with a better name though. 

Thesaurus mode! 

- `embset.names_vectors` ?
- `embset.to_X_names` ?

Preference?

**Comment by mkaze** [comment]
I think `embset.to_names_X` and `embset.from_names_X` would be good.

**Comment by koaning** [comment]
That certainly feels consistent. Agreed!
