### ISSUE TITLE
Using `fit_transform` in Ivis and Tsne transformers implementation

### ISSUE THREAD

**Issue by mkaze** [RasaHQ/whatlies#172]
Shouldn't [here][1] and [here][2] the `transform` be used instead of `fit_transform`?! Otherwise it would refit on the (possibly new) given embeddingset and therefore produce wrong results; am I right?

[1]: https://github.com/RasaHQ/whatlies/blob/6100d271162297fc6876dc5dc17a8b56ddb1f173/whatlies/transformers/tsne.py#L55
[2]: https://github.com/RasaHQ/whatlies/blob/6100d271162297fc6876dc5dc17a8b56ddb1f173/whatlies/transformers/ivis.py#L60

**Comment by koaning** [comment]
I think `TSNE` does not implement `.transform()` [docs](https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html). You must retrain on every dataset.

**Comment by koaning** [comment]
For `IVIS` this does seem to be possible. [docs](https://bering-ivis.readthedocs.io/en/latest/api.html).

**Comment by mkaze** [comment]
> I think TSNE does not implement .transform() docs. You must retrain on every dataset.

I see. I always thought it creates an embedding space (which I think is indeed the case since it has a `embedding_` attribute in sklearn). So it could use that space to embed new data (e.g. like PCA)! I postpone reading the inner workings of TSNE for a long time; maybe I should read the paper soon!

> For IVIS this does seem to be possible. docs.

So I think it's reasonable to use that instead.

**Comment by mkaze** [comment]
From the shape of `embedding_` attribute (`embedding_ : array-like, shape (n_samples, n_components)`) it could be inferred that the embeddings are per sample and not per component; so that's where it's different.

**Comment by koaning** [comment]
Yeah `TSNE` has some unintuitive bits. If I recall correctly you can also only have 2 or 3 dimensions as output as well. This is why I have a slight preference to `UMAP`.
