### ISSUE TITLE
The "bluee"!

### ISSUE THREAD

**Issue by mkaze** [RasaHQ/whatlies#177]
Apparently [there is this typo][1] in the repository which has occurred 43 times in 20 files (probably due to copy-pasting). I don't know if it should be fixed or not.

[1]: https://github.com/RasaHQ/whatlies/search?q=bluee&unscoped_q=bluee

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @amn41 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by amn41** [comment]
thanks for catching! @koaning can you please review :)

**Comment by koaning** [comment]
Ah yeah, that's an awkward typo. I might argue that it's not the end of the world, but I'll gladly accept any PR that addresses it.

**Comment by Ayushsunny** [comment]
hello @koaning Sir I have made a new PR https://github.com/RasaHQ/whatlies/pull/304 
can you review it now please

**Comment by koaning** [comment]
This is now fixed.
