### ISSUE TITLE
Style checks on the Cron Job

### ISSUE THREAD

**Issue by koaning** [RasaHQ/whatlies#178]
It feels like the style checking mechanisms in our CI are not in sync with the Cronjob. I think it makes sense not to test for style in our Cronjob but the fact that they disagree is worrying. Worthy to investigate. 

https://github.com/RasaHQ/whatlies/runs/1034192166

**Comment by mkaze** [comment]
I think this issue could be closed now because it turned out the `black` was to blame (#186).
