### ISSUE TITLE
Add tests for the interactive charts

### ISSUE THREAD

**Issue by koaning** [RasaHQ/whatlies#183]
@mkaze recently introduced some tests for matplotlib based charts, it's time that we also do that for the ones based on Altair. This issue is a place where we can discuss what properties to test.

**Comment by mkaze** [comment]
I'll take this one! :)

**Comment by koaning** [comment]
@mkaze can I close this issue?

**Comment by mkaze** [comment]
@koaning Actually, I haven't added the tests for `plot_movement` yet.
