### ISSUE TITLE
Mention scikit-learn API compatibility the readme

### ISSUE THREAD

**Issue by rth** [RasaHQ/whatlies#184]
Thanks for this very nice package!

It would be nice to mention the scikit-learn API compatibility in the readme. 

If you are interested in a user story in the interacting with the documentation. 

I knew there was a package that produced embedding from text in a scikit-learn pipeline. Found it via github search, looked at the the readme and documentation couldn't find anything about it. Though I had the wrong package continued looking in other packages. Finally, double checked that this was indeed the package mentioned in the announcement tweet. After more carefully checking the documentation finally found the corresponding [docs](https://rasahq.github.io/whatlies/tutorial/scikit-learn/). The conclusions is that,
 - mentioning this feature in the readme can be useful, while a long description of related project might be more useful as a separate documentation page instead of being on the documentation home page.
 - one horizontal menu and one (and sometimes two) vertical sub-menu in the documentation is nice once one figures out how to use them, but they can be somewhat confusing for a fraction of users after a superficial glance at the docs

**Comment by koaning** [comment]
Thanks for reaching out! I'm happy to hear you find the feature useful. 

The scikit-learn feature is certainly useful, but there's a reason why I prefer not putting it front and center. It works with `Pipeline` but breaks with `GridSearchCV`. This is a pretty big caveat. The goal of this library will always be closer to explaining and visualizing. We currently do not have the bandwidth to offer proper general support for scikit-learn. I'm not even 100% sure it is possible (not every language backend will pickle the way scikit-learn likes it). I suppose it cannot hurt to mention in the documentation but it is not the core goal of the package, rather mere a feature for now. 

I'm interesting in redo-ing the readme file soon-ish though. Do you have an example of a readme file that contains a horizontal menu and/or vertical sub-menus?

**Comment by rth** [comment]
> The scikit-learn feature is certainly useful, but there's a reason why I prefer not putting it front and center. 

Fair enough. I'm just saying it could be helpful for potential users if the readme/homepage provided a more complete summary of the supported features. For instance, for people looking to compute the embedding of multiple tokens with different embedding types (e.g. fasttext, transformers, etc).

>  Do you have an example of a readme file that contains a horizontal menu and/or vertical sub-menus?

I meant the documentation. Not saying that this needs fixing, I was likely distracted, but it might still give a data point on usability :)

Feel free to close this issue.

**Comment by koaning** [comment]
I've made a PR to update the readme. It now has a feature list and it lists the scikit-learn support at the bottom. 

https://github.com/RasaHQ/whatlies/pull/185

Once this is reviewed/merged I'll close this issue.
