### ISSUE TITLE
add color to plot_interactive_matrix

### ISSUE THREAD

**Issue by koaning** [RasaHQ/whatlies#19]
This property is currently missing. We should check if Altair allows for this.

**Comment by Raghibshams456** [comment]
https://github.com/RasaHQ/whatlies/pull/80#issuecomment-657704910

**Comment by Raghibshams456** [comment]
Have used plot_interactive(). configure (background='red')
@koaning  will this work...?

**Comment by koaning** [comment]
The goal of this feature is to add color to the points depending on the properties that are in the embeddingset. `.plot_interactive` currently has this featre `.plot_interactive_matrix` does not.

**Comment by tttthomasssss** [comment]
@koaning does this include support for label information? For example, I can add PoS tag information to each word in the embedding set and have that information colour coded in the plot. Would also be awesome at the sentence level, i.e. visualise the label information (i.e. Intent labels) when generating the plot.

**Comment by koaning** [comment]
In essense, yes! 

You first need to add a property to a word embedding at the moment. The current API for that is described [here](https://rasahq.github.io/whatlies/api/embeddingset/#whatlies.embeddingset.EmbeddingSet.add_property). 

You will need to manually specify a function that can "attach" the POS/label/property to each embedding but it's very flexible.

**Comment by koaning** [comment]
That said @tttthomasssss , the interactive matrix chart does not support colors yet. Anybody interested in contributing this feature can look at the implementation in `plot_interactive` for inspiration on how to solve it for the matrix plot as well.
