### ISSUE TITLE
Rename internal files to prevent import errors.

### ISSUE THREAD

**Issue by caseybasichis** [RasaHQ/whatlies#194]
Testing the examples in Notebook, I'm encountering an error on the UMAP example.  Any ideas?

```from whatlies.transformers import pca, umap

# orig_chart = emb.plot_interactive('man', 'woman')
pca_plot = emb.transform(pca(2)).plot_interactive('pca_0', 'pca_1')

emb.transform(umap(2)).plot_interactive('umap_0', 'umap_1')
```

```TypeError                                 Traceback (most recent call last)
<ipython-input-5-18f8db210390> in <module>
      2 
      3 # orig_chart = emb.plot_interactive('man', 'woman')
----> 4 pca_plot = emb.transform(pca(2)).plot_interactive('pca_0', 'pca_1')
      5 
      6 emb.transform(umap(2)).plot_interactive('umap_0', 'umap_1')

TypeError: 'module' object is not callable```

**Comment by koaning** [comment]
Ah! This is a capitalisation issue. From the top of my head:

```python
from whatlies.transformer import Pca
pca_plot = emb.transform(Pca(2)).plot_interactive('pca_0', 'pca_1')
```

This is because the `Pca` object is implemented over at `whatlies.transformer.pca`. We should correct this because this is a common error. It would be better if our internal files followed the following name convention: `whatlies.transformer._pca`. This way you'd not get this error.

**Comment by koaning** [comment]
Would you mind if I change the name of this issue to reflect the internal name change that needs to happen?

**Comment by caseybasichis** [comment]
That did the trick. Thank you!  Feel free to change the issue name.

I'm loving the library btw -- word analysis has taken the place of sleep this evening.

**Comment by koaning** [comment]
I'm happy to hear you enjoy the library! 

If you ever end up doing something interesting with our tool, feel free to reach out and share it with us. We're trying to collect interesting examples [here](https://rasahq.github.io/whatlies/examples/lipstick-pig/) and we're certainly open to contributions.
