### ISSUE TITLE
Handle helper vectors added by some of the transformer classes

### ISSUE THREAD

**Issue by mkaze** [RasaHQ/whatlies#199]
There was this small discussion [here](https://github.com/RasaHQ/whatlies/issues/125#issuecomment-685452160) about how to handle helper vectors, such as `pca_0`, `pca_1` etc., added by some of the transformer classes. Now we can discuss it here in a dedicated issue to find out how we want to go about handling them.

@koaning I think both of us could not found a use case for them, especially after the integer axis support has been added. However, I think you might fear that something comes up in the future that proves the otherwise. Now, what's your final thought on this? If you prefer to make them optional, what's your suggested way of implementing it? Adding a keyword argument to `__init__`? And should they be added by default or not?

**Comment by koaning** [comment]
When I think about it long and hard ... I might be able to come up with a use-case. The thing with the "pca"-vectors is that you can analyse them afterwards. Thinking of things like "what is the pca for genendered words" vs. "what is the pca for slurs" and "do these two pca-spans correlate" I guess it could still be useful. Now ... it took me a while to come up with this use-case (and it is very much a niche-case) ... so I think it's better to just remove them. 

The main thinking here is "keep the complicated things complicated, if that means the simple things remain simple". It's a design rule I've thought myself in other projects and I think it applies here. You can still manually to the above research with our library, it just involves more custom python code. The goal of the library should not be to make the niche edge cases simpler if that means the common things become complex as a result. 

Let's remove them :)

**Comment by mkaze** [comment]
> When I think about it long and hard ... I might be able to come up with a use-case. The thing with the "pca"-vectors is that you can analyse them afterwards. Thinking of things like "what is the pca for genendered words" vs. "what is the pca for slurs" and "do these two pca-spans correlate" I guess it could still be useful.

I think I couldn't follow this. Can you please provide an example of how these indicator vectors could be useful in the scenario you mentioned?

> Let's remove them :)

All right, I'll work on a PR for this.
