### ISSUE TITLE
3D matplotlib charts

### ISSUE THREAD

**Issue by koaning** [RasaHQ/whatlies#200]
I'm not 100% sure about this feature but I wanted a place to discuss it. 

I recently made 3D charts to explain the geometry behind the debiasing technique and why I think it doesn't work as one might expect.

![image](https://user-images.githubusercontent.com/1019791/92369663-94ab5200-f0f9-11ea-853e-216664eebcff.png)

![image](https://user-images.githubusercontent.com/1019791/92369678-97a64280-f0f9-11ea-9b2c-2b86e0f73860.png)

I'm drawing over the 3D matplotlib charts here, but it definately seems like I'm able to tell a better story because of these charts. Might be good to start thinking about how we might be able to support them here.

**Comment by mkaze** [comment]
@koaning In my opinion, one of the cornerstones for improvement of this library is its visualization capabilities (alongside two other cornerstones: 1- additional methods or modules for better/easier exploration and understanding, 2- well-written application guides). So I strongly support this one in general.

**Comment by koaning** [comment]
What might be a nice name for such a method? 

```
embset.plot_3d()
embset.plot_3d_mpl()
```

The reason for bringing it up: there may be other backends that offer this as well.

**Comment by koaning** [comment]
@mkaze I could start working on this since I've got the code ready anyway. Two questions;

1. What might be the appropriate method name `.plot_3d()`? 
2. The same question, but now keeping the unified API in mind.

**Comment by mkaze** [comment]
> 1. What might be the appropriate method name `.plot_3d()`?

Yes, I think `plot_3d` is a good name.

> 2. The same question, but now keeping the unified API in mind.

Well, I was thinking about implementing this in the `plot` method as well by adding an additional `z_axis` argument which could be optional (with a default value of `None`, unlike `x_axis` and `y_axis`, to plot 2D charts by default). This is [consistent with matplotlib API](https://matplotlib.org/mpl_toolkits/mplot3d/tutorial.html) as well; but I can't foresee all the obstacles in this path without implementing it myself (though, I know it's possible to do!), and you might have a better picture as you have already implemented it. And further, this would be also useful if we decide in the future to have an API like `embset.plot.scatter`, `embset.plot.arrow`, `embset.plot.distance`, etc.

**Comment by koaning** [comment]
This is where the details might get tricky. If you supply the `.plot()` method with three axes ... should we then make a "3d"-plot or a "scatter-matrix"-plot like `.plot_interactive_matrix`? 

With that in mind I think `.plot_3d` might be preferable because it's somewhat "obvious" what the plot is supposed to do.

**Comment by mkaze** [comment]
> This is where the details might get tricky. If you supply the .plot() method with three axes ... should we then make a "3d"-plot or a "scatter-matrix"-plot like .plot_interactive_matrix? 

To me the answer is clear: matrix plot is another kind of plot and therefore it should have a separate API like `plot_matrix` (which we already don't support it for matplotlib but it could be easily done). I just searched and found out that [Pandas also distinguish this](https://pandas.pydata.org/docs/reference/api/pandas.plotting.scatter_matrix.html). Further, I think the `z_axis`, when put besides `x_axis` and `y_axis`, has a clear meaning even to the newbie users.

> With that in mind I think .plot_3d might be preferable because it's somewhat "obvious" what the plot is supposed to do.

As I said, this is a good option if that's your preference. We can implement something now, and then change it later if we decide to overhaul the visualization API. There is always room for refactoring and deprecation :smile:

**Comment by koaning** [comment]
This feature has now been added.
