### ISSUE TITLE
Remove `show_axis_point` from plotting methods. 

### ISSUE THREAD

**Issue by koaning** [RasaHQ/whatlies#206]
We've before mentioned the desire to remove transformers that add extra features. I'm now reminded that part of the transition will also require us to remove the `show_axis_point`from a lot of our visualisation methods.

**Comment by mkaze** [comment]
Although it might be still relevant and valid, i.e. since the axis could be an embedding in general, but I also cannot imagine a good reason for a user not wanting to include the axis projection vectors in the plot; so it might be useless to have that argument.
