### ISSUE TITLE
Assign should also allow for values. 

### ISSUE THREAD

**Issue by koaning** [RasaHQ/whatlies#228]
Would we be opposed to allowing this? 

```python
embset.assign(property=1)
```

As opposed to this: 

```python
embset.assign(property=lambda e: 1)
```

I still want to support the latter due to the flexibility. But the direct value could be a more consise way of dealing with it many use-cases surrounding adding a property to add a color to a plot.

**Comment by mkaze** [comment]
I am also in favor of it (having callables and non-callables as the value of property) since I don't see any harm in supporting that, and potentially, as you mentioned, it might simplify the use cases where all the embeddings should have the same property value.
