### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by hashirabdulbasheer** [RasaHQ/whatlies#261]
Hi, 

There are two issues related to the installation.

1) pip3 install whatlies[transformers]
zsh: no matches found: whatlies[transformers]

2) I am getting an error compiling llvmlite when I try to install whatlies with pip3.
command: pip3 install whatlies
os: Mac 

here is the complete output

Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-install-w0wcu_al/llvmlite/setup.py'"'"'; __file__='"'"'/private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-install-w0wcu_al/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-wheel-hxzzmvey
       cwd: /private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-install-w0wcu_al/llvmlite/
  Complete output (26 lines):
  running bdist_wheel
  /usr/local/opt/python@3.9/bin/python3.9 /private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-install-w0wcu_al/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-install-w0wcu_al/llvmlite/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 420, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 501, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-install-w0wcu_al/llvmlite/ffi/build.py", line 191, in <module>
      main()
    File "/private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-install-w0wcu_al/llvmlite/ffi/build.py", line 185, in main
      main_posix('osx', '.dylib')
    File "/private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-install-w0wcu_al/llvmlite/ffi/build.py", line 107, in main_posix
      raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/usr/local/opt/python@3.9/bin/python3.9' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite, numba, umap-learn, whatlies
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-install-w0wcu_al/llvmlite/setup.py'"'"'; __file__='"'"'/private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-install-w0wcu_al/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-record-oy35___h/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/llvmlite
         cwd: /private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-install-w0wcu_al/llvmlite/
    Complete output (29 lines):
    running install
    running build
    got version from file /private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-install-w0wcu_al/llvmlite/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /usr/local/opt/python@3.9/bin/python3.9 /private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-install-w0wcu_al/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-install-w0wcu_al/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-install-w0wcu_al/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-install-w0wcu_al/llvmlite/ffi/build.py", line 185, in main
        main_posix('osx', '.dylib')
      File "/private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-install-w0wcu_al/llvmlite/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/local/opt/python@3.9/bin/python3.9' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-install-w0wcu_al/llvmlite/setup.py'"'"'; __file__='"'"'/private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-install-w0wcu_al/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/27/1jd5jx3d5jz9nhhr3ky571km0000gn/T/pip-record-oy35___h/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/llvmlite Check the logs for full command output.

Any idea? I am running it local on a MacBook.

thanks
hashir

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by mkaze** [comment]
> pip3 install whatlies[transformers]
zsh: no matches found: whatlies[transformers]

Basically, since you are using `zsh` shell, you should quote the package part due to brackets, like:
```
pip install 'whatlies[transformers]'
```
Please see [this relevant answer](https://stackoverflow.com/a/30539963/2099607) on SO.

**Comment by mkaze** [comment]
> I am getting an error compiling llvmlite when I try to install whatlies with pip3.
command: pip3 install whatlies
os: Mac

What is your `pip3` version? (use `pip3 --version` to find out) Try upgrading `pip3`, i.e. using `pip3 install -U pip`, and see if the issue is resolved.

**Comment by hashirabdulbasheer** [comment]
Thanks a lot for that. I was able to proceed with transformers after that. 
But it stopped again with the error in building llvmlite.

**Comment by hashirabdulbasheer** [comment]
I am using pip3 version

pip3 --version
pip 20.2.4 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)

**Comment by hashirabdulbasheer** [comment]
I upgraded pip3, but its still the same error. Could it be due to python 3.9 ?

**Comment by mkaze** [comment]
Sorry, I am not using Mac. But [this](https://github.com/numba/llvmlite/issues/531) and [this](https://github.com/numba/llvmlite/issues/621) issues might be relevant. @koaning Any ideas?

**Comment by hashirabdulbasheer** [comment]
It was definitely a python 3.9 problem. Those tickets mention that too. I installed python 3.8 and everything went along smoothly. So its solved now.

thanks a lot for the help.
