### ISSUE TITLE
Installing from source is broken

### ISSUE THREAD

**Issue by synapticarbors** [RasaHQ/whatlies#320]
When installing from the source distribution (.tar.gz) rather than the wheel, there is an error due to the `readme.md` not being in the source distribution:

```
pip install --no-binary :all: whatlies
```

```
Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ld/gx_8s3_n25g1dkhj59zjlxww0000gn/T/pip-install-j1jgucid/whatlies_d4b383e945574b47b346e62542fc3c0d/setup.py", line 67, in <module>
        long_description=pathlib.Path("readme.md").read_text(),
      File "/Users/xyz/miniconda2/envs/foo/lib/python3.9/pathlib.py", line 1266, in read_text
        with self.open(mode='r', encoding=encoding, errors=errors) as f:
      File "/Users/xyz/miniconda2/envs/foo/lib/python3.9/pathlib.py", line 1252, in open
        return io.open(self, mode, buffering, encoding, errors, newline,
      File "/Users/xyz/miniconda2/envs/foo/lib/python3.9/pathlib.py", line 1120, in _opener
        return self._accessor.open(self, flags, mode)
    FileNotFoundError: [Errno 2] No such file or directory: 'readme.md'
```

I would recommend adding a `MANIFEST.in` file to specify that the readme is included:
https://packaging.python.org/guides/using-manifest-in/

**Comment by koaning** [comment]
I've always wondered what those files are for 😅 .

**Comment by koaning** [comment]
I've just added it to the project, could you confirm if this should suffice? If so I'll push a new patched version.

**Comment by synapticarbors** [comment]
I think that should work

**Comment by koaning** [comment]
Grand. I'll be fixing some unit tests and pushing once it's done :)

**Comment by koaning** [comment]
I just pushed version 0.6.5 with the fix. Thanks for reporting :)

**Comment by sugatoray** [comment]
@koaning I had started packaging `whatlies` for conda-forge and this error happened there. Thanks to @synapticarbors, the root-cause of this error was identified and then it got fixed. The build just passed with the base requirements of `whatlies`.
