### ISSUE TITLE
SpacyLanguage does not create embeddings for single token

### ISSUE THREAD

**Issue by Arsilla** [RasaHQ/whatlies#5]
When making embeddings using the SpacyLanguage class the vectors are not created correctly:

```lang = SpacyLanguage("en_core_web_sm")
lang['red'].vector
>>> []
```

It's because in the `__getitem___` function the end token is set to -1, but array[0,-1] returns [] for single entries. So the new_str is empty.

```a = np.array([0, 1])
print(a[0:-1])
 >>> [0]

a = np.array([0])
print(a[0:-1])
 >>>[]
```

**Comment by koaning** [comment]
d0h.

**Comment by koaning** [comment]
probably a good idea at this point to start thinking about some unit tests. this is a nice one.

**Comment by koaning** [comment]
Which spacy vectors are you using here by the way?

**Comment by Arsilla** [comment]
Uhhh, does that matter? I think the English md model that’s also in your readme. But I can check later if you need to know for sure.

**Comment by koaning** [comment]
<img width="918" alt="image" src="https://user-images.githubusercontent.com/1019791/76013294-fbb43800-5f17-11ea-8216-f1c423f8a083.png">

nah that was also a bug. 

tis also fixed ...
