### ISSUE TITLE
How to plot a graph in a non interactive mode ?

### ISSUE THREAD

**Issue by rmiaouh** [RasaHQ/whatlies#58]
Hi guys, thank for whatlies and your work.

I have a question, is it possible to use the plot function in a non interactive mode ?
And is it possible to save directly a plot as image ?

Thank for all.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @dakshvar22 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
That's certainly a feature I can add. Just so I understand, what is your use-case here? Understanding your usecase makes it easier for me to add the feature in a useful way for you.

In the meantime, altair does offer ways to export the chart. I've made a gif; 

![Kapture 2020-06-17 at 9 18 33](https://user-images.githubusercontent.com/1019791/84867492-865e1480-b07b-11ea-9686-4ef07b1f9df7.gif)

Does this cover your usecase?

**Comment by rmiaouh** [comment]
@koaning , first of all , thank for your amazing work.

> what is your use-case here?

My use-case is to automate the creation of PDF files. In these files i want to add the result of whatlies plots. Why ? Because i use a LOT of NER spacy models and i want to see the difference beetween my models. But i don't want to do it one by one in an interactive mode (like in your gif method).

Again, thk for your work and your answer,
R.

**Comment by koaning** [comment]
Ah I see. 

In that case it might be nice to mention that the visualisations are altair visualisations. You get back the reference to the plot object when you call `.plot_interactive()`. This means that you can overwrite the properties by calling `.plot_interactive().properties(...)` but also that you can save it in whatever format you like. 

I've written a small tutorial on [my blog](https://calmcode.io/altair/json.html) on how to do this for html and json but you can also do this for svg. You can find a reference in the [altair docs](https://altair-viz.github.io/user_guide/saving_charts.html?highlight=save%20svg#png-svg-and-pdf-format). The final code will eventually be something like;

```
embset.plot_interactive(...).save('chart.svg')
embset.plot_interactive(...).save('chart.png')
```

I could add such an example to the documentation but knowing this, do you still think there's a usecase for turning the interactivity off?

**Comment by koaning** [comment]
Also, out of curiosity. How did you find out about this project?

**Comment by rmiaouh** [comment]
Thk for your answer @koaning,

i installed altair_saver, but when i try to use it, i got an error , did i miss something ?

My code "test_whatlies.py" :+1: 
```
from whatlies.language import SpacyLanguage
from altair_saver import save

words = ["prince", "princess", "nurse", "doctor", "banker", "man", "woman",
         "cousin", "neice", "king", "queen", "dude", "guy", "gal", "fire",
         "dog", "cat", "mouse", "red", "bluee", "green", "yellow", "water",
         "person", "family", "brother", "sister"]

lang = SpacyLanguage("en_core_web_md")
emb = lang[words]

emb.plot_interactive('man', 'woman').save("chart.png")
```
the error : 

![image](https://user-images.githubusercontent.com/43033520/84881987-e4482780-b08e-11ea-9c48-bb9a7cd9ee6a.png)



-----------------

> I could add such an example to the documentation

Yes please, that would be perfect.

>  but knowing this, do you still think there's a usecase for turning the interactivity off?
I will try a bit more whatlies (because i use it since yesterday) and i will come back to answer this question.

> Also, out of curiosity. How did you find out about this project?
Your project is amazing, you need more popularity, i found your lib in the rasa blogpost. To be honest i need a lib like whatlies since 1 year and you did it, i tried the tensorflow embeding chart but this is not the perfect use case for me. WHatlies is perfect. I will come back if i have new features for you. 

--------------------------
Also, is there a miss spelling in this exemple ?
https://rasahq.github.io/whatlies/tutorial/embeddingsets/

![image](https://user-images.githubusercontent.com/43033520/84882597-c929e780-b08f-11ea-8b8b-cd134d22534d.png)

`from whatlies.language.language import SpacyLanguage`

Thk for all

**Comment by koaning** [comment]
Good call on the spelling error. I'll release a new version next week (new embedding backend) and the change will be live by then. 

I'll keep this issue here and will check it out later, it feels like altair should be able to fix it. The fix will probably occur next week though. We've got a conference tomorrow: https://www.l3-ai.dev/ ( just menioning it -> it's a free event and I'll be around the digital stand should you want to discuss issues face/face).

**Comment by rmiaouh** [comment]
@koaning Thk for all

> We've got a conference tomorrow: https://www.l3-ai.dev/ ( just menioning it -> it's a free event and I'll be around the digital stand should you want to discuss issues face/face).

I will try to come, but my english is not really good ( i'm french ahahahah).

__________________________


```
from whatlies.language import SpacyLanguage
from altair_saver import save

words = ["prince", "princess", "nurse", "doctor", "banker", "man", "woman",
         "cousin", "neice", "king", "queen", "dude", "guy", "gal", "fire",
         "dog", "cat", "mouse", "red", "bluee", "green", "yellow", "water",
         "person", "family", "brother", "sister"]

lang = SpacyLanguage("en_core_web_md")
emb = lang[words]

emb.plot_interactive('man', 'woman').save("./chart.png")
```
Also, I solved this problem, I had to change `.save("chart.png")` to `.save("**./chart.png**")` and I forgot to install this npm package  `npm install vega-lite vega-cli canvas`

Again, thk for your work and for your help, I will continue to work with whatlies, and come back if I have other questions/requests.

R

**Comment by koaning** [comment]
Just to ping. I've now referenced to this issue and added an FAQ to the project documentation [here](https://rasahq.github.io/whatlies/faq/).
