### ISSUE TITLE
BERT embeddings are not contextualized

### ISSUE THREAD

**Issue by Arsilla** [RasaHQ/whatlies#6]
Currently when using the 'sentence input with [token] input as this' put into the `SpacyLanguage` class does not result in the contextualized word embedding, since it will only input `token` into the model:

```
np.array_equal(bert['Going to the [store]'].vector, 
               bert['[store] this in the drawer please.'].vector)
>>> True
```
Spacy with Bert embeddings returns the context embedding using the token index:

```
np.array_equal(bertje('Going to the store')[3],
               bertje('store this in the drawer please.')[0])
>>> False
```

**Comment by koaning** [comment]
Yep. This is a clear bug. Probably something wrong I am doing with the translating.

**Comment by Arsilla** [comment]
AFAIK you need to input the whole sentence and use the index to get one token. The vector for the whole thing is then what would have been the CLS output in the original model (I’m guessing).

**Comment by koaning** [comment]
Progress. 

```
from whatlies.language import SpacyLanguage

lang = SpacyLanguage("en_trf_robertabase_lg")
np.array_equal(
  lang.nlp("Going to the store")[3], 
  lang.nlp("Store this in the drawer")[0]
) # False 
```

The error is in my code.

**Comment by koaning** [comment]
whoa. yep. that was totally a bug on my side. fixed now tho. 

<img width="832" alt="image" src="https://user-images.githubusercontent.com/1019791/76012351-6ebcaf00-5f16-11ea-924c-df29814f4621.png">
