### ISSUE TITLE
"make develop" fails due to model mismatch

### ISSUE THREAD

**Issue by mkaze** [RasaHQ/whatlies#62]
Currently, running `make develop` would install the small English model of spaCy (i.e. `en_core_web_sm`); however, the `tests/prepare_disk_for_tests.py` uses the medium version (i.e. `en_core_web_md`). This conflict results in the `make develop` command to fail in a clean development installation. Which one is intended to be used in the tests, the small or the medium version? It's also worth mentioning that in the notebooks only the small model have been used.

If you would like, I can push the fix as a PR.

**Comment by koaning** [comment]
The notebooks can be ignored, I want to port that content to the docs and remove the `.ipynb` files in the medium term. I think it's fine to use `en_core_web_md` as a standard for spaCy here. 

Feel free to make the PR. Thanks :) !
