### ISSUE TITLE
"files" option in pre-commit config for black hook

### ISSUE THREAD

**Issue by mkaze** [RasaHQ/whatlies#63]
A pattern, i.e. `files: sklego`, has been set for the filenames to be checked by `black` hook. Essentially, this makes `black` to skip all the files because nothing would match with that pattern. I was wondering if this is intentional or not.

If this is a mistake, I can work on a PR to fix it as well as run a check on all the files; however, let me know if you want to only the package files to be checked, i.e. set  `files: whatlies`, or include the tests as well, i.e. no need to set `files` option in that case.

**Comment by koaning** [comment]
Ah yeah good catch! The sklego there refers to [another project that I maintain](https://scikit-lego.readthedocs.io/en/latest/). Feel free to fix that one.
