### ISSUE TITLE
The concept of "royal"/"royalty"

### ISSUE THREAD

**Issue by mkaze** [RasaHQ/whatlies#65]
In the [second notebook][1] as well as in the [embeddings tutorial][2], two concepts have been defined using word embeddings:

```python
royalty = tokens['king'] - tokens['queen']
gender = tokens['man'] - tokens['woman']
```
Although, denoting `"man" - "woman"` as the concept/vector of "gender" looks more or less fine and valid to me, but denoting `"king" - "queen"` as the concept/vector of "royalty" seems intuitively confusing and misleading to me (instead, it would basically represent the "gender" concept as well). 

My argument is that basically both "king" and "queen" have the concept of "royalty" in them and therefore when we subtract one from the other this would cancel out, of course assuming a linear relationship. In other words, considering an intuitive understanding of word embedding mathematics and the relation "man is to king as woman is to queen", it would make more sense to denote "royalty" concept using either of `"king" - "man"` or `"queen" - "woman"` instead.

I would appreciate if you could provide your point of view and correct me if I am wrong.

[1]: https://github.com/RasaHQ/whatlies/blob/master/notebooks/02-towards-embeddings.ipynb
[2]: https://github.com/RasaHQ/whatlies/blob/master/docs/tutorial/embeddings/index.md

**Comment by koaning** [comment]
Ai. I fear those notebooks are slightly dated and are generally not maintained. I do agree with your sentiment tough. 

I personally find it more interesting to project entire embeddingsets. You should be able to do something like;

```
emb_debias = emb | (emb['man'] - emb['woman']) 
```

Depending on the embedding that you started with you should now have an embedding where 

```
emb_debias['king'] ~= emb_debias['queen']
```

You should be careful with the meaning behind operations though. I made this library to visualise the effects but you should be careful with analogies. For example, do these hold?

```
babycorn = corn + small 
icetea = tea - hot + cold
```

You can try it out for for yourself with [this api](https://rasahq.github.io/whatlies/api/language/fasttext_lang/#whatlies.language.fasttext_lang.FasttextLanguage.score_similar). If you take fasttext then; 

```
new_emb = emb['king'] - emb['man'] + emb['woman']
```

This new embedding is closer to "king" than "queen".

**Comment by mkaze** [comment]
> You should be careful with the meaning behind operations though. I made this library to visualise the effects but you should be careful with analogies. For example, do these hold?
> 
> ```
> babycorn = corn + small 
> icetea = tea - hot + cold
> ```

Of course, I agree that these analogies may not hold generally and for every word emebedding model, and also they may not be extensible as well. That's basically because these models are not **explicitly trained** to satisfy these analogies; the objective function is something else which does not explicitly take into account these relationships which we expect. However, my point about `king - queen` was more about the consistency in the **intuitive** understanding of word embedding analogies (which I think you share the same view).

> 
> You can try it out for for yourself with [this api](https://rasahq.github.io/whatlies/api/language/fasttext_lang/#whatlies.language.fasttext_lang.FasttextLanguage.score_similar). If you take fasttext then;
> 
> ```
> new_emb = emb['king'] - emb['man'] + emb['woman']
> ```
> 
> This new embedding is closer to "king" than "queen".

Yeah, actually it turns out that the "queen" is the second-closest! I remember Ian Goodfellow mentioned this a while ago: https://twitter.com/goodfellow_ian/status/1134842227711025152?lang=en

Thank you for your reply and sharing your thoughts! I'll close this as I think my concern is resolved now.
