### ISSUE TITLE
Feature request: add parameter to `plot_scatter` to turn text on/off

### ISSUE THREAD

**Issue by Arsilla** [RasaHQ/whatlies#7]
It'd be nice to have an option to turn annotations on for the scatter plot.
Basically what you get now if you plot scatter and text on top of each other.

for example:
![image](https://user-images.githubusercontent.com/26546344/75995452-bb938c00-5efc-11ea-9505-f82f050d7271.png)

**Comment by koaning** [comment]
What do you mean with an annotation here?

**Comment by koaning** [comment]
You want the dots to go away and only have the text?

**Comment by Arsilla** [comment]
No I want what’s in the screenshot. Currently I can only plot only text or only dots.

**Comment by koaning** [comment]
The api allows for this. 

Tried this? 
```
(embeddings
  .plot('scatter', emb['foo'], emb['bar'])
  .plot('text', emb['foo'], emb['bar']))
```

**Comment by koaning** [comment]
I do agree that a text setting might be a better api. But I want to check if this works on your machine first.

**Comment by Arsilla** [comment]
Yes I did but I just thought it was a clunky way to do it...

**Comment by koaning** [comment]
Fair enough. I'll this this issue as a reminder but I will rename it slightly :)

**Comment by koaning** [comment]
I might also change the api to something like; 

```
emb.plot_scatter(backend=...)
emb.plot_arrow(backend=...)
emb.plot_bars(backend=...)
```

**Comment by Arsilla** [comment]
I agree that would be better. It feels counter intuitive put the type first in the arguments with the current api, and the x and y second. So emb.plot_scatter(x, y, *args) would make more sense.
