### ISSUE TITLE
Feature request: plot graph to visualise distance

### ISSUE THREAD

**Issue by Arsilla** [RasaHQ/whatlies#9]
I've always been a fan of using networkx to create graphs for my vector embeddings.
The networkx implementation of the kamada kawai graph layout allows you to input a dictionary containing the distance of each node to the others (eg: {0: {0:0, 1: .01}, 1: {1:0, 0:, 0.1}}), which it then tries to visualise in a good way.
So what I often do is calculate for example the cosine distances to be used as input. This can give a nice visual on the similarity based on distance:

![image](https://user-images.githubusercontent.com/26546344/76192214-93987700-61e1-11ea-8dc5-542014eb83e5.png)

My quick code for this on the embedding set (which doesn't work for the api you made but I'll leave that to you :) ):

```
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def plot_graph(self):
        plt.figure(figsize=(10, 10))
        vectors = [token.vector for k, token in self.embeddings.items()]
        label_dict = {i: w for i, (w, _) in enumerate(self.embeddings.items())}
        dist = cosine_distances(np.array(vectors), np.array(vectors))
        # Greate graph
        G = nx.from_numpy_matrix(dist)
        distance = pd.DataFrame(dist).to_dict()
        # Chhange laytout positions of the graph
        pos = nx.kamada_kawai_layout(G, dist=distance)
        # Draw nodes and labels
        nx.draw_networkx_nodes(G, pos, node_color='b', alpha=0.5)
        nx.draw_networkx_labels(G, pos, labels=label_dict, font_color='w')
```

Let me know what you think! I like it when dealing with high dimensional vectors.

**Comment by koaning** [comment]
would i be correct in saying this is like one of those graph layout things?

**Comment by koaning** [comment]
i am thinking about also having support for not just mapping unto vectors, but also calculating the cosine distance between them as a plotting mechanism. 

if you'd like to achieve github points, feel free to make a PR of that function. maybe call it "plot_graph_layout"

**Comment by Arsilla** [comment]
Literarily said so in the second sentence haha, so yes. Expect I don't draw the edges, just the nodes. You could but then they would all just be connected to each other, which doesn't add much to the visual. 

wrt your last comment, I'll see if I have some time tonight to do that.

**Comment by koaning** [comment]
are there multiple layouts available in networkx that are relevant? when i was doing graph stuff i recall doing a whole lot of force directed layout-ing

**Comment by Arsilla** [comment]
I can check if there's any others, but most of them don't utilize any distance input as far as I remember. 
I'll let you know I run into any issues. Are you fine with this function existing as is or should it be called in a similar way as plot? (as in, the actual plotting happens on the embedding level. Since that might be quite challenging).

**Comment by koaning** [comment]
@Arsilla I would be perfectly fine with this plot working only on the `EmbeddingSet` level. I would appreciate it though if we have a seperate function (say, `plot_graph_layout()`) that is called by a method (say `EmbeddingSet.plot_graph_layout()`). There's a gut feeling that says it will be easier to maintain/come up with test cases that way.

**Comment by koaning** [comment]
this went in.
