### ISSUE TITLE
spacy language backend sometimes produces wrong embeddings

### ISSUE THREAD

**Issue by mkaze** [RasaHQ/whatlies#91]
The problem is that the embeddings given by the `SpacyLanguage` backend may not be correct in all cases. That's because currently a whitespace tokenizer [is used](1) for finding the position of tokens, whereas each language model in spaCy has its own tokenizer which might be more sophisticated than just a simple whitespace splitting. To demonstrate this, consider the following examples (note that the BERT model from `spacy-transformers` have been used here because the first two examples concern contextualized embeddings; however, it does not make a difference to use a built-in spaCy model instead):

```python
import numpy as np
from whatlies.language import SpacyLanguage

lang = SpacyLanguage("en_trf_bertbaseuncased_lg")

# =========================================
# Example 1
query_raw = "let's go [home]"
query_clean = "let's go home"
emb = lang[query_raw]
doc = lang.model(query_clean)
print(list(doc))
# [let, 's, go, home]

assert str(doc[2]) == 'go'
assert str(doc[3]) == 'home'
# In correct case, the following two statements should raise exception
assert np.array_equal(emb.vector, doc[2].vector)
assert not np.array_equal(emb.vector, doc[3].vector)

# =========================================
# Example 2
query_raw = "player #10 [won]"
query_clean = "player #10 won"
emb = lang[query_raw]
doc = lang.model(query_clean)
print(list(doc))
# [player, #, 10, won]

assert str(doc[2]) == '10'
assert str(doc[3]) == 'won'
# In correct case, the following two statements should raise exception
assert np.array_equal(emb.vector, doc[2].vector)
assert not np.array_equal(emb.vector, doc[3].vector)

# =========================================
# Example 3: even when there is no context emb
query_raw = "pre-order this product"
emb = lang[query_raw]
doc = lang.model(query_raw)
print(list(doc))
# [pre, -, order, this, product]

assert str(doc[:-2]) == "pre-order"
# In correct case, the following two statements should raise exception
assert np.array_equal(emb.vector, doc[:-2].vector)
assert not np.array_equal(emb.vector, doc.vector)
```
Note that we used an English model above, and spaCy supports multiple languages which might have complex tokenization rules beyond whitespace tokenization and we may not be aware of them (although we can look them up in the source code but that's not the point); so, we cannot just blame these non-alphanumeric characters (e.g. `'`, `#`, `-`, `?`, `!`) in English for the cause of this issue and treat these examples as special cases.

**Solution:** This issue happens because we want to provide contextualized embeddings (which, so far, only makes sense for `spacy-transformer` models), but we are not using the model's tokenizer (i.e. `lang.model.tokenizer`) to find the position of requested tokens. This could be solved by first tokenizing the raw query to find the position of `[` and `]` tokens and their enclosed tokens, and then clean the query string and use the model to find the embeddings of the enclosed tokens (of course, this works with the assumption that the user is formatting the sentence correctly; e.g. `how[are] you` would be tokenized as `['how[are', ']', 'you']`, I guess that's a fair assumption to make).

Another option is to drop the support for `spacy-transformers` entirely and therefore there would be no need for contextualized embeddings, especially if hugginface would be supported in near(!) future. However, personally I don't like this option especially because `spacy-transformers` provides alignment of embeddings from wordpieces to tokens (although, I think this is not something so special such that we cannot implement it ourselves in huggingface backend).

Anyways, I would be happy to work on a PR for the fix.

[1]: https://github.com/RasaHQ/whatlies/blob/6a9d4857ac0815f5d0179c7e3aba03b4e9a7909c/whatlies/language/spacy_lang.py#L18-L20

**Comment by sara-tagger** [comment]
Thanks for the issue, @rctatman will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by koaning** [comment]
There's a bigger discussion around this topic and I should admit that I haven't 100% figured this out yet. I came up with the `[bank] of the river` syntax a while ago because at the time it seemed like a cool way to do it. This was in a time before I realised how different tokenisers might have all sorts of different standards. Especially the BERT stuff can get really tricky here. 

For spaCy models I'd certainly agree that the models tokenizer from spaCy would be a better place to start but a larger discussion might need to happen first ... do we like the `[bank] of the river`-syntax? 

Pros:
- it's pretty easy to understand and might work for most cases 
- we can have the same 'api' for dealing with the selection of specific words

Cons: 
- there have been texts that contain `[`-characters and this would totally break 
- string parsing can be messy 
- how to deal with all these different tokenizers

**Comment by mkaze** [comment]
> there have been texts that contain [-characters and this would totally break

Yeah, that's true.

> string parsing can be messy

No, since we would use tokenizer and it would be just a one line call. Although, I think this additional step (i.e. first determining whether brackets have been used and are properly formatted, and then finding their position) decreases the performance especially when large number of samples is provided.

> how to deal with all these different tokenizers

At least spaCy models come with their own tokenizers (i.e. could be accessed with `.tokenizer` attribute). For models which don't have it, we can default to whitespace tokenizer (or if we want to go further, we can provide the ability for the user to set a tokenizer method, using say `set_tokenizer(callback)`).

> different languages might not appreciate this syntax

That's also something to consider.

All in all, personally I am not for this feature especially if we decide to provide the ability to get the embeddings for tokens in a sentence (i.e. #92); and also considering the fact that the user usually cannot automatically annotate a large number of samples for contextual emebddings, so it might be used for one or a few samples (so instead give the user all the token embeddings in a sentence and let them decide whatever they want to do with them; that would be equivalent and also provide more freedom for the user).

**Comment by koaning** [comment]
I do want to offer an easy way for people to select a subset of an utterance, say "[bank] of the river" vs. "money on the [bank]", and that you still get a single embedding. The moment that you need to manually track tokens it's going to get error prone and also "not fun to use". This feature is meant for people who have a small set of data and would like to demo to stakeholders how this tech works (I've actually gotten feedback that this is why some people like this library). 

This is more of a "user-interface" argument than a "functionality" argument, but it is something I find important for this library. I'm fine with adding an interface for getting an embedding for each token but that's a "complicated" usecase from where I am standing.

**Comment by mkaze** [comment]
> This is more of a "user-interface" argument than a "functionality" argument, but it is something I find important for this library. I'm fine with adding an interface for getting an embedding for each token but that's a "complicated" usecase from where I am standing.

Fair enough. I don't have access to user feedback, so that's why I miss these viewpoints!
Although, I think it's a good idea to provide a **temporary fix** for this issue (assuming for the moment that the square bracket syntax is not going to change, until a better alternative would be found).

**Comment by koaning** [comment]
I think an `.embed()` method as described in https://github.com/RasaHQ/whatlies/issues/92 could offer a more flexible API towards that use-case.

**Comment by koaning** [comment]
Can this issue now be closed?
